### ISSUE TITLE
Volunteer list

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/Liverpool-Makefest-2017#1]
List of volunteers with times available (Friday evening, Saturday morning, Saturday afternoon, other)

**Comment by Pezmc** [comment]
<strike>I don't have anything to exhibit, though I am seeking a project (anyone need a ✋ ? 😄). I'm happy to volunteer on the day for whatever is needed. Available Friday evening and all day Saturday.</strike>

I just went to mark the 24th in my calendar, and realised that I'm away, so I'm not available at all, sorry for the noise! Still more than happy to help out between now and the event though.

**Comment by JackiePease** [comment]
That’s great Pez – There’s loads of stuff to help with. Are you in on Maker night?

**Comment by Pezmc** [comment]
Did you see my update on Github @jackie1050? Looks like you may have replied by email. I realised I'm not actually free for the event but can help up until it.

I'm aware of maker night but unfortunately it clashes with a Meetup group I host so am yet to attend, I'm going to see if I can sneak out early this evening and head across to DoES for a bit!

**Comment by JackiePease** [comment]
You’re right – I only looked at the email. Great that you’ll be able to help in the run up anyway. Hope to see you soon and we can discuss (I’ll be in on Saturday too).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
