### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/Liverpool-Makefest-2017#10]
Could be good to show videos we already have:

- [x] Find suitable videos (e.g. Ethos)
- [ ] Television on stand to display them

**Comment by amcewen** [comment]
It'd be good to see if we can get a version of the Ethos video with subtitles on it, as I think it'd be better to have videos without sound, agree?

I've asked for a copy of it anyway.

We can also produce a video from a bunch of still images too - showing each one for a few seconds, so if someone collects them all into one place I'm happy to compile a single video combining it all which we can then just play on loop...  Maybe some of Jane MacNeil's photos would be good?

The "TV on stand" could also be a laptop or monitor on the table...

**Comment by amcewen** [comment]
I've got a copy of the Ethos film.  They don't have a version with subtitles.  If I get ambitious I might try adding some...

**Comment by JackiePease** [comment]
Great, and I'll get in touch with Jane

**Comment by amcewen** [comment]
No need, she's already given us copies of all her photos.  We just need to choose which ones would be useful - http://www.janemacneil.co.uk/blog-liverpool-photography/2017/2/5/does-liverpool has the set to choose from I think.

**Comment by JackiePease** [comment]
Seán will put together a slideshow of images and testimonials if possible

**Comment by DoESsean** [comment]
@amcewen will show me how to put subtitles on a video.

**Comment by DoESsean** [comment]
I've put a message out to the Google Group asking for phots or testimonials, and will email Made In Liverpool to see if they're ok with us using their videos of DoES and the Wearables Group as part of the loop.

Actually, I'll email Laura too and make sure she's fine with it as well.

**Comment by jamieisboss** [comment]
I have a tv stand kind of like [this one](https://images-na.ssl-images-amazon.com/images/I/41WaNoBJc1L.jpg) that would probably work well for this, i have a 32" tv that went on it that isn't being used but i've been told it flickers so would have to test.

Also for the content, [Screenly Open Source Edition](https://www.screenly.io/ose/) might be an easy way of managing content for the screen
