### ISSUE TITLE
List of exhibitors

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/Liverpool-Makefest-2017#2]
List of exhibitors with description of item/dimensions/delivery arrangements/power/wifi

**Comment by amcewen** [comment]
I'll be bringing...
 * Ackers Bell.  Needs power and WiFi.  Approx space 30x30cm
 * Bubblino.  Needs power and Ethernet.  Approx space 30x20cm
 * Museum in a Box.  Needs power.  Approx space 50x30cm
 * The Electric Liver Bird.  Needs power.  Not sure where this is going to sit, but @SayBeano asked me to bring it t'other day, so I'm sure they'll find room :-)

**Comment by huffeec** [comment]
I'll bring;
Pinhole cameras x2 ~100x150mm and 40x100mm
Contour map 300x300mm
Both already in DoES, neither need power/wifi

**Comment by ajlennon** [comment]
I'm hoping to bring a subset of

Glimpse - i.MX6 based WiFi Bodycam unit(s)
eCall - headless In vehicle cellular emergency calling device (IVS)
BinBot - headless cellular waste disposal monitoring system(s)
e-Paper - display based on ESP8266 module

3in NXP Kinetis based touchscreen display
3in NXP i.MX6 based touchscreen display
7in NXP i.MX6 embedded computer with display and touchscreen, running Android
