### ISSUE TITLE
Labels for exhibits

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/Liverpool-Makefest-2017#8]
Small stand up labels with name of exhibitor / description of exhibit?

- [x] Make card holders
- [x] Collect descriptions from exhibitors
- [x] Print/laser cut labels

**Comment by amcewen** [comment]
Ones that stand up would be great.  In case it's useful, I've stashed the previous style we've used "somewhere safe" - https://github.com/DoESLiverpool/somewhere-safe/tree/master/events#exhibit-labels

**Comment by JackiePease** [comment]
Thanks to Jamie (a different Jamie) for making 20 small card holders from scrap acrylic

**Comment by jackie1050** [comment]
Still need to make labels

**Comment by DefProc** [comment]
@jackie1050 I've just been doing a "mail merge for Inkscape templates" for the official MakeFest posters, would something similar be useful for generating DoES's labels?

If so, I've put together a [google spreadsheet to collect the details](https://docs.google.com/spreadsheets/d/1Shh42EFP3nMiW4gl09GxYrjqYToIDtuDAYZKMEBPNic/edit?usp=sharing), and I'll run up a template to work from.

**Comment by DefProc** [comment]
Actually, if it's easier, here's a web form link to collect the details: https://goo.gl/forms/6GrtFrDAkM8KT1q73
