### ISSUE TITLE
Posters

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/Liverpool-Makefest-2017#9]
E.g.:

- [ ] Introduction to DoESLiverpool, prices, times etc.
- [ ] Profiles of some users (coworking space / workshop)
- [ ] Explanation of how the Knitic works

**Comment by JackiePease** [comment]
Seán will do DoESLiverpool poster
Still need someone to do Knitic poster

**Comment by ajlennon** [comment]
From @jackie1050 - didn't do this
